name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} # Use login shell for all steps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Mambaforge environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.11"
          environment-file: environment.yml
          mamba-version: "*"
          activate-environment: commercial-sar
          auto-update-conda: true
          channel-priority: "strict"

      - name: Lint with Ruff
        run: ruff check .

      - name: Format check with Ruff
        run: ruff format --check .

      - name: Run tests with Pytest
        run: pytest
